# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('portfolio_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestoneDimensionMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('project_milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_milestones', to='portfolio_manager.ProjectMilestone')),
            ],
        ),
        migrations.RemoveField(
            model_name='numericdimensionmilestone',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='numericdimensionprogress',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_manager.Organization'),
        ),
        migrations.AlterField(
            model_name='numericdimensionprogress',
            name='numeric_dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='portfolio_manager.NumericDimension'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='portfolio_manager.Project'),
        ),
    ]
