# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='parent',
            new_name='organization',
        ),
    ]
