# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0002_auto_20161203_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumericDimensionChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=256)),
                ('change', models.IntegerField()),
                ('numeric_dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='portfolio_manager.NumericDimension')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='numericdimensionprogress',
            name='numeric_dimension',
        ),
        migrations.DeleteModel(
            name='NumericDimensionProgress',
        ),
    ]
