# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0002_auto_20161207_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='organization',
            new_name='parent',
        ),
    ]
