# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0002_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='Name',
        ),
    ]
