# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0002_auto_20170111_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectownerdimension',
            name='assPerson',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='portfolio_manager.AssociatedPersonDimension'),
            preserve_default=False,
        ),
    ]
