# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0003_auto_20161129_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio_manager.Organization'),
            preserve_default=False,
        ),
    ]
