# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0003_auto_20161204_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numericdimensionchange',
            name='numeric_dimension',
        ),
        migrations.RenameField(
            model_name='numericdimension',
            old_name='initial_value',
            new_name='value',
        ),
        migrations.DeleteModel(
            name='NumericDimensionChange',
        ),
    ]
