# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0003_projectownerdimension_assperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsertedField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('textValue', models.CharField(max_length=50)),
                ('numericalValue', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_manager.Project')),
            ],
        ),
    ]
