# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 12:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('portfolio_manager', '0003_auto_20161207_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedPersonDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecimalDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecimalDimensionMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MembersDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MilestonesDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumericDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumericDimensionMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('numeric_dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='portfolio_manager.NumericDimension')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDependenciesDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestoneDimensionMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('project_milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_milestones', to='portfolio_manager.ProjectMilestone')),
            ],
        ),
        migrations.CreateModel(
            name='StartTimeDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SuppliersDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('suppliers', models.ManyToManyField(to='portfolio_manager.Supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('task_description', models.TextField()),
                ('value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_manager.Organization'),
        ),
        migrations.CreateModel(
            name='CustomerDimension',
            fields=[
                ('textdimension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_manager.TextDimension')),
            ],
            options={
                'abstract': False,
            },
            bases=('portfolio_manager.textdimension',),
        ),
        migrations.CreateModel(
            name='DescriptionDimension',
            fields=[
                ('textdimension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_manager.TextDimension')),
            ],
            options={
                'abstract': False,
            },
            bases=('portfolio_manager.textdimension',),
        ),
        migrations.CreateModel(
            name='DevelopmentMethodDimension',
            fields=[
                ('textdimension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_manager.TextDimension')),
            ],
            options={
                'abstract': False,
            },
            bases=('portfolio_manager.textdimension',),
        ),
        migrations.CreateModel(
            name='OwningOrganizationDimension',
            fields=[
                ('textdimension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_manager.TextDimension')),
            ],
            options={
                'abstract': False,
            },
            bases=('portfolio_manager.textdimension',),
        ),
        migrations.CreateModel(
            name='PhaseDimension',
            fields=[
                ('textdimension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_manager.TextDimension')),
            ],
            options={
                'abstract': False,
            },
            bases=('portfolio_manager.textdimension',),
        ),
        migrations.CreateModel(
            name='ProjectManagerDimension',
            fields=[
                ('associatedpersondimension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_manager.AssociatedPersonDimension')),
            ],
            options={
                'abstract': False,
            },
            bases=('portfolio_manager.associatedpersondimension',),
        ),
        migrations.CreateModel(
            name='ProjectOwnerDimension',
            fields=[
                ('associatedpersondimension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_manager.AssociatedPersonDimension')),
            ],
            options={
                'abstract': False,
            },
            bases=('portfolio_manager.associatedpersondimension',),
        ),
        migrations.CreateModel(
            name='SizeImpactDimension',
            fields=[
                ('textdimension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_manager.TextDimension')),
            ],
            options={
                'abstract': False,
            },
            bases=('portfolio_manager.textdimension',),
        ),
        migrations.CreateModel(
            name='SizeMd',
            fields=[
                ('decimaldimension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_manager.DecimalDimension')),
            ],
            options={
                'abstract': False,
            },
            bases=('portfolio_manager.decimaldimension',),
        ),
        migrations.CreateModel(
            name='SizeMoneyDimension',
            fields=[
                ('decimaldimension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_manager.DecimalDimension')),
            ],
            options={
                'abstract': False,
            },
            bases=('portfolio_manager.decimaldimension',),
        ),
        migrations.CreateModel(
            name='TechnologyDimension',
            fields=[
                ('textdimension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_manager.TextDimension')),
            ],
            options={
                'abstract': False,
            },
            bases=('portfolio_manager.textdimension',),
        ),
        migrations.AddField(
            model_name='projectdimension',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='portfolio_manager.Project'),
        ),
        migrations.AddField(
            model_name='projectdependenciesdimension',
            name='dependencies',
            field=models.ManyToManyField(to='portfolio_manager.Project'),
        ),
        migrations.AddField(
            model_name='milestonesdimension',
            name='milestones',
            field=models.ManyToManyField(related_name='milestones_dimensions', to='portfolio_manager.ProjectMilestone'),
        ),
        migrations.AddField(
            model_name='membersdimension',
            name='members',
            field=models.ManyToManyField(to='portfolio_manager.Person'),
        ),
        migrations.AddField(
            model_name='decimaldimensionmilestone',
            name='numeric_dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decimal_milestones', to='portfolio_manager.DecimalDimension'),
        ),
        migrations.AddField(
            model_name='associatedpersondimension',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_manager.Person'),
        ),
    ]
