# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0004_auto_20161204_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='membersdimension',
            name='members',
            field=models.ManyToManyField(to='portfolio_manager.Person'),
        ),
    ]
