# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0004_auto_20161129_1038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
