# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0005_auto_20161129_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.CharField(default='p', max_length=50),
        ),
    ]
