# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0005_auto_20161205_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestonesDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='projectmilestone',
            name='project',
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='milestones_dimension',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='portfolio_manager.MilestonesDimension'),
            preserve_default=False,
        ),
    ]
