# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0006_auto_20161201_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='p', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='organization',
        ),
        migrations.AddField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(default='p', on_delete=django.db.models.deletion.CASCADE, related_name='org', to='portfolio_manager.Organization'),
        ),
    ]
