# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0007_auto_20161201_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='id',
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='p', max_length=50, primary_key=True, serialize=False),
        ),
    ]
