# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0008_auto_20161207_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestonesdimension',
            name='milestones',
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='milestones_dimension',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='portfolio_manager.MilestonesDimension'),
            preserve_default=False,
        ),
    ]
