# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0009_auto_20161207_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmilestone',
            name='milestones_dimension',
        ),
        migrations.AddField(
            model_name='milestonesdimension',
            name='milestones',
            field=models.ManyToManyField(related_name='milestones_dimension', to='portfolio_manager.ProjectMilestone'),
        ),
    ]
