# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0009_auto_20161201_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='org', to='portfolio_manager.Organization'),
        ),
    ]
