# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0010_auto_20161207_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='pets',
        ),
        migrations.AlterField(
            model_name='milestonesdimension',
            name='milestones',
            field=models.ManyToManyField(related_name='milestones_dimensions', to='portfolio_manager.ProjectMilestone'),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
