# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0011_auto_20161201_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='id',
            field=models.AutoField(auto_created=True, default='p', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
