# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 08:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0011_auto_20161209_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecimalDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecimalDimensionMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDependencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('depends_on', models.ManyToManyField(to='portfolio_manager.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectManagerDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_manager.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('task_description', models.TextField()),
                ('value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('textdimension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_manager.TextDimension')),
            ],
            options={
                'abstract': False,
            },
            bases=('portfolio_manager.textdimension',),
        ),
        migrations.CreateModel(
            name='Deliverer',
            fields=[
                ('textdimension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_manager.TextDimension')),
            ],
            options={
                'abstract': False,
            },
            bases=('portfolio_manager.textdimension',),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('textdimension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_manager.TextDimension')),
            ],
            options={
                'abstract': False,
            },
            bases=('portfolio_manager.textdimension',),
        ),
        migrations.CreateModel(
            name='DevelopmentMethod',
            fields=[
                ('textdimension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_manager.TextDimension')),
            ],
            options={
                'abstract': False,
            },
            bases=('portfolio_manager.textdimension',),
        ),
        migrations.CreateModel(
            name='PhaseDimension',
            fields=[
                ('textdimension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_manager.TextDimension')),
            ],
            options={
                'abstract': False,
            },
            bases=('portfolio_manager.textdimension',),
        ),
        migrations.CreateModel(
            name='SizeImpact',
            fields=[
                ('textdimension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_manager.TextDimension')),
            ],
            options={
                'abstract': False,
            },
            bases=('portfolio_manager.textdimension',),
        ),
        migrations.CreateModel(
            name='SizeMd',
            fields=[
                ('decimaldimension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_manager.DecimalDimension')),
            ],
            options={
                'abstract': False,
            },
            bases=('portfolio_manager.decimaldimension',),
        ),
        migrations.CreateModel(
            name='SizeMoney',
            fields=[
                ('decimaldimension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_manager.DecimalDimension')),
            ],
            options={
                'abstract': False,
            },
            bases=('portfolio_manager.decimaldimension',),
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('textdimension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_manager.TextDimension')),
            ],
            options={
                'abstract': False,
            },
            bases=('portfolio_manager.textdimension',),
        ),
        migrations.AddField(
            model_name='decimaldimensionmilestone',
            name='numeric_dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decimal_milestones', to='portfolio_manager.DecimalDimension'),
        ),
    ]
