# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0013_auto_20161201_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='t', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_manager.Organization'),
        ),
    ]
