# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0014_auto_20161209_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartTimeDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
