# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0015_starttimedimension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starttimedimension',
            name='value',
            field=models.DateTimeField(),
        ),
    ]
