# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0016_auto_20161209_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOwnerDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_manager.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='projectmanagerdimension',
            name='manager',
        ),
        migrations.AddField(
            model_name='projectmanagerdimension',
            name='value',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portfolio_manager.Person'),
            preserve_default=False,
        ),
    ]
