# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0017_auto_20161209_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanagerdimension',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_manager.Person'),
        ),
        migrations.AlterField(
            model_name='projectownerdimension',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_manager.Person'),
        ),
    ]
