# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0020_auto_20161209_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associatedpersondimension',
            old_name='values',
            new_name='value',
        ),
    ]
