# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0021_auto_20161209_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwningOrganization',
            fields=[
                ('textdimension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio_manager.TextDimension')),
            ],
            options={
                'abstract': False,
            },
            bases=('portfolio_manager.textdimension',),
        ),
    ]
