# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0022_owningorganization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OwningOrganization',
            new_name='OwningOrganizationDimension',
        ),
    ]
