# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0023_auto_20161209_1004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectDependencies',
            new_name='ProjectDependenciesDimension',
        ),
        migrations.RenameField(
            model_name='projectdependenciesdimension',
            old_name='depends_on',
            new_name='dependencies',
        ),
    ]
