# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0024_auto_20161209_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SuppliersDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('suppliers', models.ManyToManyField(to='portfolio_manager.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='DelivererDimension',
        ),
    ]
