# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0025_auto_20161209_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliersdimension',
            name='suppliers',
            field=models.ManyToManyField(to='portfolio_manager.Supplier'),
        ),
    ]
