# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0026_auto_20161209_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliersdimension',
            name='suppliers',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='SuppliersDimension',
        ),
    ]
