# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0028_suppliers_suppliersdimensions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suppliers',
            new_name='Supplier',
        ),
        migrations.RenameModel(
            old_name='SuppliersDimensions',
            new_name='SuppliersDimension',
        ),
    ]
